# **1. PLM**
PLM(Pre-trained Language Model)은 대량의 텍스트 데이터를 사전 학습하여 자연어 이해와 생성 능력을 갖춘 인공지능 모델입니다. 대표적으로 BERT, GPT, T5 등이 있으며, 이들은 대규모 데이터에서 단어의 의미와 문맥을 학습한 후, 특정 작업(예: 문장 분류, 번역, 질의응답 등)에 맞게 추가 학습(Fine-tuning)하여 활용됩니다. PLM은 문맥을 고려한 자연어 처리 능력이 뛰어나며, 다양한 언어 기반 AI 애플리케이션에서 핵심 기술로 사용됩니다.

### 1. BERT

[BERT(Bidirectional Encoder Representations from Transformers)](https://arxiv.org/pdf/1810.04805)는 구글에서 개발한 사전 훈련된 자연어 처리(NLP) 모델로, Transformer 아키텍처를 기반으로 양방향 문맥 이해가 가능하도록 설계되었습니다. 기존 NLP 모델들은 단어의 앞 또는 뒤 방향으로만 문맥을 고려하는 경우가 많았지만, BERT는 문장의 양쪽 방향에서 동시에 문맥을 학습하여 더 정교한 언어 이해가 가능합니다. BERT는 두 가지 주요 사전 훈련 기법인 Masked Language Model(MLM)과 Next Sentence Prediction(NSP)을 사용하여 텍스트의 의미를 효과적으로 학습하며, 이를 통해 다양한 NLP 태스크(예: 문장 분류, 개체명 인식, 질의응답 시스템 등)에 적용될 수 있습니다. 또한, BERT는 기본적으로 사전 훈련된 후 특정 작업(Task-Specific Fine-tuning)을 통해 원하는 NLP 태스크에 맞게 미세 조정(fine-tuning)할 수 있어 강력한 성능을 발휘합니다.

### 2. GPT

GPT(Generative Pre-trained Transformer)는 OpenAI에서 개발한 사전 훈련된 자연어 처리(NLP) 모델로, Transformer 아키텍처를 기반으로 한 자동회귀(Auto-regressive) 모델입니다. GPT는 대량의 텍스트 데이터로 사전 훈련을 수행한 후, 특정 태스크(Task-Specific Fine-tuning) 없이도 문장 생성, 번역, 요약 등 다양한 언어 관련 작업을 수행할 수 있습니다. 특히, GPT는 단방향 학습(unidirectional learning) 방식을 사용하여 입력된 문맥을 기반으로 다음 단어를 예측하며 텍스트를 생성하는데, 이는 챗봇, 스토리 생성, 코드 자동 완성 등 창의적인 콘텐츠 생성에 강력한 성능을 발휘합니다. GPT 시리즈는 버전이 업그레이드될수록 모델 크기와 성능이 향상되었으며, 특히 GPT-3와 GPT-4는 대규모 데이터를 활용한 학습으로 더욱 정교한 언어 이해와 생성 능력을 갖추고 있습니다.

# **2. Hugging Face**
Hugging Face는 자연어 처리(NLP)와 머신러닝(ML) 모델을 쉽게 활용할 수 있도록 지원하는 오픈소스 플랫폼이자 AI 회사입니다. 대표적으로 Transformers 라이브러리를 통해 BERT, GPT, T5 등 다양한 사전 학습된 모델을 제공하며, Datasets 라이브러리로 다양한 데이터셋을 효율적으로 활용할 수 있습니다. 또한, Hugging Face Hub에서는 연구자와 개발자들이 AI 모델과 데이터셋을 공유할 수 있으며, Gradio와 Spaces를 활용해 간단한 웹 애플리케이션으로 AI 모델을 배포할 수도 있습니다. PyTorch와 TensorFlow를 모두 지원하며, AI 연구 및 애플리케이션 개발을 보다 쉽게 만들어주는 강력한 도구입니다.

### 1. Hugging Face 모델 허브

[Hugging Face 모델 허브](https://huggingface.co/models)는 BERT, GPT, T5, Stable Diffusion 등 다양한 사전 학습된 AI 모델을 제공하는 공개 플랫폼입니다. 사용자는 자연어 처리(NLP), 컴퓨터 비전, 음성 인식 등 다양한 분야의 모델을 검색하고, PyTorch 또는 TensorFlow와 함께 손쉽게 활용할 수 있습니다. 모델마다 설명, 예제 코드, 라이선스 정보가 제공되며, 직접 학습한 모델을 업로드하거나 다른 연구자들이 공유한 모델을 다운로드하여 활용할 수도 있습니다. 이를 통해 연구자와 개발자는 AI 모델을 빠르게 실험하고 실제 애플리케이션에 적용할 수 있습니다. 검색창에 'ko' 또는 'kor'를 입력하여 한국어 모델을 서치할 수 있습니다.

### 2. Hugging Face를 이용한 토큰화

Hugging Face의 각 모델은 각 모델과 맵핑되는 토크나이저가 존재합니다. A모델을 사용한다면 A모델의 토크나이저를 사용해야 합니다. 각 토크나이저는 Vocabulary 정보를 담고 있으므로 A모델에 B토크나이저를 사용할 경우, 입력을 이해하지 못하는 상황이 발생합니다. 예를 들어 A모델은 단어 '사과'가 3번이고, B모델은 단어 '사과'가 51번인데, 입력으로 '사과가 먹고싶다'라는 문장이 들어올 경우 입력의 혼선이 발생하게됩니다.

# **3. 한국어 금융 뉴스 긍정, 부정, 중립 분류하기**
금융 뉴스 문장 감성 분석 데이터셋(Finance Sentiment Corpus)은 금융 관련 뉴스 문장을 긍정(Positive), 부정(Negative), 중립(Neutral)으로 분류한 감성 분석 데이터셋입니다. 이 데이터셋은 주식시장 예측, 금융 리포트 분석, 투자 전략 수립 등을 위해 자연어 처리(NLP) 모델을 훈련하는 데 활용됩니다. 일반적으로 주식 시장의 변동성과 연관된 뉴스 기사의 영향을 분석하는 데 유용하며, 금융 전문가의 의견, 기업 실적 발표, 경제 지표 등의 내용을 감성 레이블과 함께 제공합니다.

In [1]:
!pip install transformers datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.6)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
!wget https://raw.githubusercontent.com/ukairia777/finance_sentiment_corpus/main/finance_data.csv

--2026-02-02 11:24:08--  https://raw.githubusercontent.com/ukairia777/finance_sentiment_corpus/main/finance_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1319001 (1.3M) [text/plain]
Saving to: ‘finance_data.csv’

finance_data.csv    100%[===================>]   1.26M  --.-KB/s    in 0.008s

2026-02-02 11:24:08 (154 MB/s) - ‘finance_data.csv’ saved [1319001/1319001]

In [3]:
import pandas as pd
import numpy as np
import random
import time
import datetime
import csv
import os
import torch
import torch.nn.functional as F

from tqdm import tqdm
from datasets import load_dataset
from torch.nn.utils.rnn import pad_sequence

from transformers import pipeline
from transformers import BertTokenizer
from transformers import BertForSequenceClassification, BertConfig
from transformers import get_linear_schedule_with_warmup
from datasets import Dataset
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from torch.nn.utils.rnn import pad_sequence
from torch.optim import AdamW

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, hamming_loss

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [4]:
df = pd.read_csv('finance_data.csv')
df

,labels,sentence,kor_sentence
0,neutral,"According to Gran, the company has no plans to...","Gran에 따르면, 그 회사는 회사가 성장하고 있는 곳이지만, 모든 생산을 러시아로..."
1,neutral,Technopolis plans to develop in stages an area...,테크노폴리스는 컴퓨터 기술과 통신 분야에서 일하는 회사들을 유치하기 위해 10만 평...
2,negative,The international electronic industry company ...,"국제 전자산업 회사인 엘코텍은 탈린 공장에서 수십 명의 직원을 해고했으며, 이전의 ..."
3,positive,With the new production plant the company woul...,새로운 생산공장으로 인해 회사는 예상되는 수요 증가를 충족시킬 수 있는 능력을 증가...
4,positive,According to the company's updated strategy fo...,"2009-2012년 회사의 업데이트된 전략에 따르면, Basware는 20% - 4..."
...,...,...,...
4841,negative,LONDON MarketWatch -- Share prices ended lower...,런던 마켓워치 -- 은행주의 반등이 FTSE 100지수의 약세를 상쇄하지 못하면서 ...
4842,neutral,Rinkuskiai's beer sales fell by 6.5 per cent t...,린쿠스키아의 맥주 판매량은 416만 리터로 6.5% 감소했으며 카우노 알루스의 맥주...
4843,negative,Operating profit fell to EUR 35.4 mn from EUR ...,"영업이익은 2007년 68.8 mn에서 35.4 mn으로 떨어졌으며, 선박 판매 이..."
4844,negative,Net sales of the Paper segment decreased to EU...,페이퍼 부문 순매출은 2008년 2분기 241.1 mn에서 2009년 2분기 221...
4845,negative,Sales in Finland decreased by 10.5 % in Januar...,"핀란드에서의 판매는 1월에 10.5% 감소한 반면, 국외에서의 판매는 17% 감소했다."

In [5]:
df['labels'] = df['labels'].replace({'neutral':0, 'positive':1, 'negative':2}).astype('int64')
df.head()

/tmp/ipython-input-665063934.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['labels'] = df['labels'].replace({'neutral':0, 'positive':1, 'negative':2}).astype('int64')

,labels,sentence,kor_sentence
0,0,"According to Gran, the company has no plans to...","Gran에 따르면, 그 회사는 회사가 성장하고 있는 곳이지만, 모든 생산을 러시아로..."
1,0,Technopolis plans to develop in stages an area...,테크노폴리스는 컴퓨터 기술과 통신 분야에서 일하는 회사들을 유치하기 위해 10만 평...
2,2,The international electronic industry company ...,"국제 전자산업 회사인 엘코텍은 탈린 공장에서 수십 명의 직원을 해고했으며, 이전의 ..."
3,1,With the new production plant the company woul...,새로운 생산공장으로 인해 회사는 예상되는 수요 증가를 충족시킬 수 있는 능력을 증가...
4,1,According to the company's updated strategy fo...,"2009-2012년 회사의 업데이트된 전략에 따르면, Basware는 20% - 4..."

In [7]:
train_cs, valid_cs = train_test_split(df, test_size=0.2, random_state=2026, stratify=df['labels'])
train_cs

,labels,sentence,kor_sentence
903,1,The Group also has a strong global position in...,그 그룹은 또한 다른 어업 범주에서 강력한 국제적 지위를 가지고 있다.
3523,0,"Also, CBA is to issue a benchmark, 10 year fix...",또한 CBA는 기준금리인 10년 고정금리 계약을 유로화로 발행할 예정입니다.
1345,0,Symphony Services provides development service...,Symphony Services는 Aldata GOLD를 위한 개발 서비스를 제공합니다.
2819,0,Aspocomp said it will spin off its Chinese and...,아스포콤프는 핀란드 살로공장의 일부 장비와 중국 및 인도 현지법인을 분리해 새로운 ...
4407,2,Net cash flow from operating activities was a ...,영업활동으로 인한 순현금흐름은 2009년 해당 기간의 23.3 mn에 비해 마이너스...
...,...,...,...
1676,0,Timo Penttila has been appointed new manager r...,Timo Penttila는 핀란드에 있는 노르데아 기관 고객의 자산 관리를 담당하는...
1447,1,"Upgrades include a five megapixel camera, voic...","업그레이드에는 500만 화소 카메라, 음성 컨트롤, 그리고 D패드 대신 광학 마우스..."
4217,0,"( ADPnews ) - Dec 30, 2009 - Finnish investmen...",(ADPnews) - 2009년 12월 30일 - 핀란드 투자 그룹 네오마르카 오이...
3868,0,The net sales of the Power Plants business wer...,발전소 사업의 순매출액은 2005년 7억1030만 유로였다.
4769,2,The terms of the aforementioned funding are co...,앞서 언급한 자금조달 조건은 시중은행의 현재 CDS 수준보다 상당히 낮은 수준이며 ...

In [8]:
valid_cs

,labels,sentence,kor_sentence
4030,0,Net loss in the same period in 2009 was euro18...,"2009년 같은 기간의 순손실은 1,860만 유로였다."
3834,0,The electricity requirement of networks will g...,네트워크의 전기 요구량은 새로운 모바일 세대와 함께 증가할 것입니다.
3158,0,The acquisition was financed with $ 2.56 billi...,이번 인수는 골드만삭스가 마련한 부채 25억6000만달러로 자금을 조달했다.
1514,0,Customers in a wide range of industries use ou...,전 세계 다양한 업종에 종사하는 고객들은 당사의 스테인리스 스틸과 서비스를 이용하고...
2405,0,Altimo previously agreed a similar deal with T...,알티모는 이전에 텔레노르와 유사한 계약을 체결하여 빔펠콤과 키예프스타-GSM의 지분...
...,...,...,...
4063,2,"In October, UPM reported a third-quarter net l...",10월 UPM은 2007년 1억2000만 유로에 비해 3분기 순손실이 1억1000만...
2630,0,"The Finnish company is building a 800,000 mt-y...",그 핀란드 회사는 싱가포르에 80만 mt의 바이오디젤 공장을 짓고 있다.
2100,1,Finnish financial software developer Basware O...,핀란드의 금융 소프트웨어 개발업체인 바스웨어 오이(Basware Oyj)는 오늘 자...
3427,0,"Through the Nordic Exchange, OMX offers access...",북유럽거래소를 통해 OMX는 북유럽과 발트해 증권시장의 약 80%에 접근할 수 있다.
2599,0,The company's board of directors has proposed ...,회사의 이사회는 2006년에 주당 0.12유로의 배당금을 제안했다.

In [10]:
train_cs, test_cs = train_test_split(train_cs, test_size=0.2, random_state=2026)
train_cs

,labels,sentence,kor_sentence
4176,0,"As a part of the plan, the Board of Directors ...",이사회는 그 일환으로 경영진이 인수한 지주회사 아스포매니지먼트오이에 대한 지급 지시...
2442,0,Elcoteq SE is listed on the Nasdaq OMX Helsink...,엘코텍 SE는 나스닥 OMX 헬싱키에 상장되어 있다.
4488,0,All Amer Sports companies develop and manufact...,모든 아메르 스포츠 회사들은 활동적인 스포츠 참가자들의 경기력을 향상시키는 기술적으...
2727,0,25 November 2010 - Finnish paints and coatings...,2010년 11월 25일 핀란드 페인트 및 코팅 회사인 Tikkurila Oyj(헬...
659,1,The diluted loss per share narrowed to EUR 0.2...,희석 주당손실은 유로 0.86에서 유로 0.27로 축소되었다.
...,...,...,...
4781,2,"ADPnews - Sep 28, 2009 - Finnish silicon wafer...",ADP뉴스 - 2009년 9월 28일 핀란드 실리콘 웨이퍼 제조업체 Okmetic ...
1786,1,London's leading shares today jumped almost 10...,"오늘 런던의 주요 주식은 시장이 개장함에 따라 거의 100포인트, 즉 1.7% 급등..."
3431,0,"treatment products in Usa, Canada, Mexico, Aus...","미국, 캐나다, 멕시코, 호주, 브라질의 치료 제품들 오늘, 글로벌 리서치 & 데이..."
2701,0,W+Ærtsil+Æ's aim is to serve the rapidly growi...,W+에르실+EA의 목표는 바렌츠 해 지역에서 급증하는 선박의 수와 증가하는 해양 활...
1052,0,Le Lay succeeds Walter G++nter and will be bas...,Le Lay는 Walter G++nter의 뒤를 이으며 핀란드에 기반을 둘 것이다.

In [11]:
test_cs

,labels,sentence,kor_sentence
4490,0,"In addition, we will launch a versatile online...","게다가, 우리는 전통적인 인쇄 신문을 완성하기 위해 다용도 온라인 서비스를 시작할 ..."
3889,0,"The portfolio comprises of 118,000 m2 of leasa...","이 포트폴리오는 118,000㎡의 임대 가능한 공간으로 구성되어 있으며, 공실률은 ..."
26,1,Nordea Group's operating profit increased in 2...,"노르데아그룹은 2010년 영업이익이 전년 대비 18% 증가한 36억4000만 유로,..."
2745,0,Finnish beverage company Olvi is one of the la...,핀란드 음료회사 올비는 핀란드에서 2009년 2분기 재무실적을 발표하지 않은 마지막...
2496,0,"Jukka Hienonen, the current Finnair CEO, will ...",현 핀에어 CEO인 유카 히노넨은 2010년 1월 말 사임할 예정이다.
...,...,...,...
2715,0,` Nordic infrastructure construction is one of...,` 북유럽 인프라 건설이 우리의 전략적 성장 분야 중 하나다.
1778,1,Combining the two producers will create a stro...,두 생산자를 합치면 글로벌 경쟁에 대응할 수 있는 강력한 EU 기반 비료 산업이 형...
767,1,"In addition to fireplace exports, demand for l...",벽난로 수출 외에도 안감석 수요가 연초 수준을 넘어섰고 남은 기간에도 뚜렷한 차돌 ...
4077,2,The tightened competition situation in the pro...,생산 자동화 시장의 강화된 경쟁 상황이 2006년 동안 순매출에 영향을 미쳤다고 첸...
275,1,Revenue in July to September grew 14 percent t...,지난 7월부터 9월까지의 매출액은 전년 동기 대비 14% 증가한 4억6700만 유로...

In [13]:
train_sentences = list(map(lambda x: '[CLS] ' + str(x) + ' [SEP]', train_cs['kor_sentence']))
validation_sentences = list(map(lambda x: '[CLS] ' + str(x) + ' [SEP]', valid_cs['kor_sentence']))
test_sentences = list(map(lambda x: '[CLS] ' + str(x) + ' [SEP]', test_cs['kor_sentence']))
train_sentences[:5]

['[CLS] 이사회는 그 일환으로 경영진이 인수한 지주회사 아스포매니지먼트오이에 대한 지급 지시 반대 주식발행에서 회사가 보유한 최대 33만주를 양도하기로 했다. [SEP]',
 '[CLS] 엘코텍 SE는 나스닥 OMX 헬싱키에 상장되어 있다. [SEP]',
 '[CLS] 모든 아메르 스포츠 회사들은 활동적인 스포츠 참가자들의 경기력을 향상시키는 기술적으로 진보된 제품들을 개발하고 제조한다. [SEP]',
 '[CLS] 2010년 11월 25일 핀란드 페인트 및 코팅 회사인 Tikkurila Oyj(헬: TIK1V)는 핀란드 국영 투자 회사인 Solidium Oy가 총 98만 유로에 자사의 지분 14.7%를 매각했다고 오늘 밝혔다. [SEP]',
 '[CLS] 희석 주당손실은 유로 0.86에서 유로 0.27로 축소되었다. [SEP]']

In [14]:
train_labels = train_cs['labels'].to_numpy(dtype='int64')
validation_labels = valid_cs['labels'].to_numpy(dtype='int64')
test_labels = test_cs['labels'].to_numpy(dtype='int64')
train_labels[:5]

array([0, 0, 0, 0, 1])

### ※ KLUE

[KLUE](https://klue-benchmark.com/)는 한국어 자연어 이해(NLU) 연구와 모델 성능 평가를 위해 서울대학교 NLP 연구진과 AI 연구 커뮤니티가 공개한 대표적인 한국어 벤치마크 데이터셋으로, 감정 분석·문장 분류·자연어 추론·개체명 인식·의미역 분석·관계 추출·기계 독해 등 여러 언어 이해 과제를 하나의 통합 기준으로 평가할 수 있도록 구성된 표준 말뭉치입니다. 영어의 GLUE에 대응하는 한국어 버전으로, 실제 뉴스·위키·온라인 문서 등 현실적인 한국어 문장을 기반으로 정교하게 주석(annotation)되어 있으며, 한국어 BERT·RoBERTa·ELECTRA·GPT 계열 모델의 성능을 공정하게 비교·검증하는 데 널리 사용됩니다. [[논문]](https://arxiv.org/pdf/2105.09680)

In [16]:
tokenizer = BertTokenizer.from_pretrained('klue/bert-base')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

In [18]:
MAX_LEN = 128

def data_to_tensor(sentences, labels, tokenizer):
    tokenized_texts = [tokenizer.tokenize(sent) for sent in sentences]
    input_ids = [torch.tensor(tokenizer.convert_tokens_to_ids(x)) for x in tokenized_texts]
    padded_inputs = pad_sequence(input_ids, batch_first=True, padding_value=0)

    # pad: 파이토치의 패딩 함수
    # (0, MAX_LEN - padded_inputs.shape[1])
    # 왼쪽에 몇 개, 오른쪽에 몇 개
    # 뒤에만 0을 붙여서 길이를 MAX_LEN으로 맞춤
    if padded_inputs.shape[1] < MAX_LEN:
        padded_inputs = F.pad(padded_inputs, (0, MAX_LEN - padded_inputs.shape[1]), value=0)
    else:
        padded_inputs = padded_inputs[:, :MAX_LEN]

    attention_masks = (padded_inputs != 0).float()
    tensor_inputs = padded_inputs
    tensor_labels = torch.tensor(labels)
    tensor_masks = attention_masks
    return tensor_inputs, tensor_labels, tensor_masks

In [21]:
train_inputs, train_labels, train_masks = data_to_tensor(train_sentences, train_labels, tokenizer)
validation_inputs, validation_labels, validation_masks = data_to_tensor(validation_sentences, validation_labels, tokenizer)
test_inputs, test_labels, test_masks = data_to_tensor(test_sentences, test_labels, tokenizer)

print(train_inputs[0], train_labels[0], train_masks[0])

/tmp/ipython-input-2885883043.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_labels = torch.tensor(labels)

tensor([    2,  9314,  2259,   636,  8596,  6233,  9243,  2052,  4854,  2470,
        13445,  8967,  2208,  2077, 29389, 11257,  2168,  2052,  2170,  3618,
         4589,  5317,  4138,  4313,  2311,  2375, 27135,  3769,  2116,  4747,
         2470,  3980,  5013,  2154,  2223,  2138,  8931, 31302,  2200,  1902,
         2062,    18,     3,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]) tensor(0) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [27]:
print(tokenizer.decode([0]))
print(tokenizer.decode([1]))
print(tokenizer.decode([2]))
print(tokenizer.decode([3]))
print(tokenizer.decode([4]))
print(tokenizer.decode([5]))

[PAD]
[UNK]
[CLS]
[SEP]
[MASK]
!

In [29]:
batch_size = 32

train_data = TensorDataset(train_inputs, train_masks, train_labels)
# 매 epoch 마다 섞어서 학습
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels)
validation_sampler = RandomSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)

test_data = TensorDataset(test_inputs, test_masks, test_labels)
test_sampler = RandomSampler(test_data)
test_dataloader = DataLoader(test_data, sampler=test_sampler, batch_size=batch_size)

print('학습 데이터의 크기: ', len(train_labels), len(train_data))
print('검증 데이터의 크기: ', len(validation_labels), len(validation_data))
print('테스트 데이터의 크기: ', len(test_labels), len(test_data))

학습 데이터의 크기:  3100 3100
검증 데이터의 크기:  970 970
테스트 데이터의 크기:  776 776

In [ ]:
num_labels = 3
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = BertForSequenceClassification.from_pretrained('klue/bert-base', num_labels=num_labels)
model.cuda()